import EditorCoreUIFFI
import Foundation
import XCTest

extension EditorCoreUIFFITests {
    func testLspInteractiveRequestsThrowWhenLspDisabledAndTakeReturnsNil() throws {
        let lib = try EditorCoreUIFFITestSupport.shared.loadLibrary()
        let ui = try EditorUI(library: lib, initialText: "hello", viewportWidthCells: 80)
        XCTAssertThrowsError(try ui.lspRequestHover(logicalLine: 0, logicalColumn: 0))
        XCTAssertThrowsError(try ui.lspRequestDefinition(logicalLine: 0, logicalColumn: 0))
        XCTAssertThrowsError(try ui.lspRequestDeclaration(logicalLine: 0, logicalColumn: 0))
        XCTAssertThrowsError(try ui.lspRequestTypeDefinition(logicalLine: 0, logicalColumn: 0))
        XCTAssertThrowsError(try ui.lspRequestImplementation(logicalLine: 0, logicalColumn: 0))
        XCTAssertThrowsError(try ui.lspRequestReferences(logicalLine: 0, logicalColumn: 0))
        XCTAssertThrowsError(try ui.lspRequestCompletion(logicalLine: 0, logicalColumn: 0))
        XCTAssertThrowsError(try ui.lspRequestCompletionItemResolve(itemJSON: #"{"label":"hello"}"#))
        XCTAssertThrowsError(try ui.lspRequestSignatureHelp(logicalLine: 0, logicalColumn: 0))
        XCTAssertThrowsError(try ui.lspRequestPrepareRename(logicalLine: 0, logicalColumn: 0))
        XCTAssertThrowsError(try ui.lspRequestRename(logicalLine: 0, logicalColumn: 0, newName: "world"))
        XCTAssertThrowsError(try ui.lspRequestCodeAction(startOffset: 0, endOffset: 0))
        XCTAssertThrowsError(try ui.lspRequestCodeActionResolve(actionJSON: #"{"title":"Fix"}"#))
        XCTAssertThrowsError(try ui.lspRequestExecuteCommand(commandJSON: #"{"command":"server.fix","arguments":[]}"#))
        XCTAssertThrowsError(try ui.lspRequestCodeLens())
        XCTAssertThrowsError(try ui.lspRequestCodeLensResolve(lensJSON: #"{"range":{"start":{"line":0,"character":0},"end":{"line":0,"character":1}}}"#))
        XCTAssertThrowsError(try ui.lspRequestInlayHints(startOffset: 0, endOffset: 1))
        XCTAssertThrowsError(try ui.lspRequestInlayHintResolve(hintJSON: #"{"position":{"line":0,"character":1},"label":"x"}"#))
        XCTAssertThrowsError(try ui.lspRequestDocumentLinks())
        XCTAssertThrowsError(try ui.lspRequestDocumentLinkResolve(linkJSON: #"{"range":{"start":{"line":0,"character":0},"end":{"line":0,"character":1}}}"#))
        XCTAssertThrowsError(try ui.lspRequestDocumentSymbols())
        XCTAssertThrowsError(try ui.lspRequestFoldingRanges())
        XCTAssertThrowsError(try ui.lspRequestSemanticTokensFull())
        XCTAssertThrowsError(try ui.lspRequestSemanticTokensDelta(previousResultId: "previous"))
        XCTAssertThrowsError(try ui.lspRequestSemanticTokensRange(startLine: 0, startColumn: 0, endLine: 0, endColumn: 1))
        XCTAssertThrowsError(try ui.lspRequestSelectionRange(positionsJSON: #"[{"line":0,"column":0}]"#))
        XCTAssertThrowsError(try ui.lspRequestLinkedEditingRange(logicalLine: 0, logicalColumn: 0))
        XCTAssertThrowsError(try ui.lspRequestDocumentDiagnostic())
        XCTAssertThrowsError(try ui.lspRequestWorkspaceDiagnostic())
        XCTAssertThrowsError(try ui.lspRequestDocumentColor())
        XCTAssertThrowsError(try ui.lspRequestColorPresentation(startOffset: 0, endOffset: 1, colorJSON: #"{"red":1,"green":0,"blue":0,"alpha":1}"#))
        XCTAssertThrowsError(try ui.lspRequestPrepareCallHierarchy(logicalLine: 0, logicalColumn: 0))
        XCTAssertThrowsError(try ui.lspRequestCallHierarchyIncomingCalls(itemJSON: #"{"name":"main"}"#))
        XCTAssertThrowsError(try ui.lspRequestCallHierarchyOutgoingCalls(itemJSON: #"{"name":"main"}"#))
        XCTAssertThrowsError(try ui.lspRequestPrepareTypeHierarchy(logicalLine: 0, logicalColumn: 0))
        XCTAssertThrowsError(try ui.lspRequestTypeHierarchySupertypes(itemJSON: #"{"name":"Type"}"#))
        XCTAssertThrowsError(try ui.lspRequestTypeHierarchySubtypes(itemJSON: #"{"name":"Type"}"#))
        XCTAssertThrowsError(try ui.lspRequestWorkspaceSymbols(query: "hello"))
        XCTAssertThrowsError(try ui.lspFormatDocument())
        XCTAssertThrowsError(try ui.lspFormatRange(startOffset: 0, endOffset: 1))
        XCTAssertThrowsError(try ui.lspFormatOnType(logicalLine: 0, logicalColumn: 1, trigger: "\n"))

        XCTAssertNil(try ui.lspTakeLastHoverResultJSON())
        XCTAssertNil(try ui.lspTakeLastDefinitionResultJSON())
        XCTAssertNil(try ui.lspTakeLastDeclarationResultJSON())
        XCTAssertNil(try ui.lspTakeLastTypeDefinitionResultJSON())
        XCTAssertNil(try ui.lspTakeLastImplementationResultJSON())
        XCTAssertNil(try ui.lspTakeLastReferencesResultJSON())
        XCTAssertNil(try ui.lspTakeLastCompletionResultJSON())
        XCTAssertNil(try ui.lspTakeLastCompletionItemResolveResultJSON())
        XCTAssertNil(try ui.lspTakeLastSignatureHelpResultJSON())
        XCTAssertNil(try ui.lspTakeLastSignatureHelpResult())
        XCTAssertNil(try ui.lspTakeLastPrepareRenameResultJSON())
        XCTAssertNil(try ui.lspTakeLastRenameResultJSON())
        XCTAssertNil(try ui.lspTakeLastCodeActionResultJSON())
        XCTAssertNil(try ui.lspTakeLastCodeActionResolveResultJSON())
        XCTAssertNil(try ui.lspTakeLastExecuteCommandResultJSON())
        XCTAssertNil(try ui.lspTakeLastCodeLensResultJSON())
        XCTAssertNil(try ui.lspTakeLastCodeLensResolveResultJSON())
        XCTAssertNil(try ui.lspTakeLastInlayHintsResultJSON())
        XCTAssertNil(try ui.lspTakeLastInlayHintResolveResultJSON())
        XCTAssertNil(try ui.lspTakeLastDocumentLinksResultJSON())
        XCTAssertNil(try ui.lspTakeLastDocumentLinkResolveResultJSON())
        XCTAssertNil(try ui.lspTakeLastDocumentSymbolsResultJSON())
        XCTAssertNil(try ui.lspTakeLastFoldingRangesResultJSON())
        XCTAssertNil(try ui.lspTakeLastSemanticTokensFullResultJSON())
        XCTAssertNil(try ui.lspTakeLastSemanticTokensDeltaResultJSON())
        XCTAssertNil(try ui.lspTakeLastSemanticTokensRangeResultJSON())
        XCTAssertNil(try ui.lspTakeLastSelectionRangeResultJSON())
        XCTAssertNil(try ui.lspTakeLastLinkedEditingRangeResultJSON())
        XCTAssertNil(try ui.lspTakeLastDocumentDiagnosticResultJSON())
        XCTAssertNil(try ui.lspTakeLastWorkspaceDiagnosticResultJSON())
        XCTAssertNil(try ui.lspTakeLastDocumentColorResultJSON())
        XCTAssertNil(try ui.lspTakeLastColorPresentationResultJSON())
        XCTAssertNil(try ui.lspTakeLastPrepareCallHierarchyResultJSON())
        XCTAssertNil(try ui.lspTakeLastCallHierarchyIncomingCallsResultJSON())
        XCTAssertNil(try ui.lspTakeLastCallHierarchyOutgoingCallsResultJSON())
        XCTAssertNil(try ui.lspTakeLastPrepareTypeHierarchyResultJSON())
        XCTAssertNil(try ui.lspTakeLastTypeHierarchySupertypesResultJSON())
        XCTAssertNil(try ui.lspTakeLastTypeHierarchySubtypesResultJSON())
        XCTAssertNil(try ui.lspTakeLastWorkspaceSymbolsResultJSON())
    }
}
