import AppKit
import Foundation

@MainActor
enum AttoMainMenuBuilder {
    static func build(appDelegate: AttoAppDelegate) -> NSMenu {
        let mainMenu = NSMenu()

        let appMenuItem = NSMenuItem()
        appMenuItem.identifier = NSUserInterfaceItemIdentifier(AttoAccessibilityID.menu("App"))
        mainMenu.addItem(appMenuItem)
        let appMenu = NSMenu()
        appMenuItem.submenu = appMenu
        appMenu.addItem(withTitle: "About AttoEditor", action: nil, keyEquivalent: "")
        appMenu.addItem(.separator())
        appMenu.addItem(commandItem(title: "Preferences...", commandID: "workbench.preferences", appDelegate: appDelegate))
        appMenu.addItem(commandItem(title: "Open User Settings", commandID: "settings.open_user_settings", appDelegate: appDelegate))
        appMenu.addItem(commandItem(title: "Open Workspace Settings", commandID: "settings.open_workspace_settings", appDelegate: appDelegate))
        appMenu.addItem(commandItem(title: "Validate User Settings", commandID: "settings.validate_user_settings", appDelegate: appDelegate))
        appMenu.addItem(commandItem(title: "Validate Workspace Settings", commandID: "settings.validate_workspace_settings", appDelegate: appDelegate))
        appMenu.addItem(.separator())
        appMenu.addItem(withTitle: "Quit AttoEditor", action: #selector(NSApplication.terminate(_:)), keyEquivalent: "q")

        let fileMenuItem = NSMenuItem()
        fileMenuItem.identifier = NSUserInterfaceItemIdentifier(AttoAccessibilityID.menu("File"))
        mainMenu.addItem(fileMenuItem)
        let fileMenu = NSMenu(title: "File")
        fileMenuItem.submenu = fileMenu
        fileMenu.addItem(commandItem(title: "New File", commandID: "file.new", appDelegate: appDelegate))
        fileMenu.addItem(.separator())
        fileMenu.addItem(commandItem(title: "Open Folder...", commandID: "file.open_folder", appDelegate: appDelegate))
        fileMenu.addItem(commandItem(title: "Open Recent Project...", commandID: "file.open_recent_project", appDelegate: appDelegate))
        fileMenu.addItem(commandItem(title: "Open File...", commandID: "file.open_file", appDelegate: appDelegate))
        fileMenu.addItem(commandItem(title: "Save", commandID: "file.save", appDelegate: appDelegate))
        fileMenu.addItem(commandItem(title: "Reload File", commandID: "file.reload", appDelegate: appDelegate))
        fileMenu.addItem(commandItem(title: "Pin Tab", commandID: "file.pin_tab", appDelegate: appDelegate))
        fileMenu.addItem(.separator())
        fileMenu.addItem(commandItem(title: "Close Tab", commandID: "file.close_tab", appDelegate: appDelegate))
        fileMenu.addItem(commandItem(title: "Close All Tabs", commandID: "file.close_all_tabs", appDelegate: appDelegate))
        fileMenu.addItem(commandItem(title: "Close Other Tabs", commandID: "file.close_other_tabs", appDelegate: appDelegate))
        fileMenu.addItem(commandItem(title: "Close Tabs to Right", commandID: "file.close_tabs_to_right", appDelegate: appDelegate))
        fileMenu.addItem(commandItem(title: "Move Tab Left", commandID: "file.move_tab_left", appDelegate: appDelegate))
        fileMenu.addItem(commandItem(title: "Move Tab Right", commandID: "file.move_tab_right", appDelegate: appDelegate))

        let editMenuItem = NSMenuItem()
        editMenuItem.identifier = NSUserInterfaceItemIdentifier(AttoAccessibilityID.menu("Edit"))
        mainMenu.addItem(editMenuItem)
        let editMenu = NSMenu(title: "Edit")
        editMenuItem.submenu = editMenu
        editMenu.addItem(commandItem(title: "Find...", commandID: "editor.find", appDelegate: appDelegate))
        editMenu.addItem(commandItem(title: "Replace...", commandID: "editor.replace", appDelegate: appDelegate))
        editMenu.addItem(commandItem(title: "Find in Files...", commandID: "search.find_in_files", appDelegate: appDelegate))
        editMenu.addItem(.separator())
        editMenu.addItem(commandItem(title: "Undo Last Workspace Edit", commandID: "workspace.undo_last_workspace_edit", appDelegate: appDelegate))
        editMenu.addItem(commandItem(title: "Redo Last Workspace Edit", commandID: "workspace.redo_last_workspace_edit", appDelegate: appDelegate))
        editMenu.addItem(.separator())
        editMenu.addItem(commandItem(title: "Format Document", commandID: "editor.format_document", appDelegate: appDelegate))
        editMenu.addItem(commandItem(title: "Format Selection", commandID: "editor.format_selection", appDelegate: appDelegate))
        editMenu.addItem(.separator())
        editMenu.addItem(commandItem(title: "Duplicate Line", commandID: "editor.duplicate_lines", appDelegate: appDelegate))
        editMenu.addItem(commandItem(title: "Delete Line", commandID: "editor.delete_lines", appDelegate: appDelegate))
        editMenu.addItem(commandItem(title: "Move Line Up", commandID: "editor.move_lines_up", appDelegate: appDelegate))
        editMenu.addItem(commandItem(title: "Move Line Down", commandID: "editor.move_lines_down", appDelegate: appDelegate))
        editMenu.addItem(commandItem(title: "Join Lines", commandID: "editor.join_lines", appDelegate: appDelegate))
        editMenu.addItem(commandItem(title: "Split Line", commandID: "editor.split_line", appDelegate: appDelegate))
        editMenu.addItem(.separator())
        editMenu.addItem(commandItem(title: "Indent", commandID: "editor.indent", appDelegate: appDelegate))
        editMenu.addItem(commandItem(title: "Outdent", commandID: "editor.outdent", appDelegate: appDelegate))
        editMenu.addItem(commandItem(title: "Delete to Previous Tab Stop", commandID: "editor.delete_to_prev_tab_stop", appDelegate: appDelegate))
        editMenu.addItem(commandItem(title: "Apply Snippet...", commandID: "editor.apply_snippet", appDelegate: appDelegate))
        editMenu.addItem(commandItem(title: "Snippet Next Placeholder", commandID: "editor.snippet_next_placeholder", appDelegate: appDelegate))
        editMenu.addItem(commandItem(title: "Snippet Previous Placeholder", commandID: "editor.snippet_prev_placeholder", appDelegate: appDelegate))
        editMenu.addItem(commandItem(title: "Toggle Line Comment", commandID: "editor.toggle_line_comment", appDelegate: appDelegate))

        let selectionMenuItem = NSMenuItem()
        selectionMenuItem.identifier = NSUserInterfaceItemIdentifier(AttoAccessibilityID.menu("Selection"))
        mainMenu.addItem(selectionMenuItem)
        let selectionMenu = NSMenu(title: "Selection")
        selectionMenuItem.submenu = selectionMenu
        selectionMenu.addItem(commandItem(title: "Select Word", commandID: "editor.select_word", appDelegate: appDelegate))
        selectionMenu.addItem(commandItem(title: "Select Line", commandID: "editor.select_line", appDelegate: appDelegate))
        selectionMenu.addItem(commandItem(title: "Expand Selection", commandID: "editor.expand_selection", appDelegate: appDelegate))
        selectionMenu.addItem(commandItem(title: "Expand Selection with LSP", commandID: "lsp.selection_range", appDelegate: appDelegate))
        selectionMenu.addItem(commandItem(title: "Linked Editing with LSP", commandID: "lsp.linked_editing", appDelegate: appDelegate))
        selectionMenu.addItem(.separator())
        selectionMenu.addItem(commandItem(title: "Add Cursor Above", commandID: "editor.add_cursor_above", appDelegate: appDelegate))
        selectionMenu.addItem(commandItem(title: "Add Cursor Below", commandID: "editor.add_cursor_below", appDelegate: appDelegate))
        selectionMenu.addItem(.separator())
        selectionMenu.addItem(commandItem(title: "Add Next Occurrence", commandID: "editor.add_next_occurrence", appDelegate: appDelegate))
        selectionMenu.addItem(commandItem(title: "Add All Occurrences", commandID: "editor.add_all_occurrences", appDelegate: appDelegate))

        let toolsMenuItem = NSMenuItem()
        toolsMenuItem.identifier = NSUserInterfaceItemIdentifier(AttoAccessibilityID.menu("Tools"))
        mainMenu.addItem(toolsMenuItem)
        let toolsMenu = NSMenu(title: "Tools")
        toolsMenuItem.submenu = toolsMenu
        toolsMenu.addItem(commandItem(title: "Toggle Macro Recording", commandID: "macro.toggle_recording", appDelegate: appDelegate))
        toolsMenu.addItem(commandItem(title: "Replay Last Macro", commandID: "macro.replay_last", appDelegate: appDelegate))
        toolsMenu.addItem(commandItem(title: "Save Last Macro As…", commandID: "macro.save_named", appDelegate: appDelegate))
        toolsMenu.addItem(commandItem(title: "Replay Named Macro…", commandID: "macro.replay_named", appDelegate: appDelegate))
        toolsMenu.addItem(commandItem(title: "Rename Named Macro…", commandID: "macro.rename_named", appDelegate: appDelegate))
        toolsMenu.addItem(commandItem(title: "Delete Named Macro…", commandID: "macro.delete_named", appDelegate: appDelegate))
        toolsMenu.addItem(commandItem(title: "Delete Named Macros…", commandID: "macro.delete_named_batch", appDelegate: appDelegate))
        toolsMenu.addItem(commandItem(title: "Undo Macro Delete", commandID: "macro.undo_delete", appDelegate: appDelegate))
        toolsMenu.addItem(commandItem(title: "Show Deleted Macros…", commandID: "macro.show_delete_history", appDelegate: appDelegate))
        toolsMenu.addItem(commandItem(title: "Manage Deleted Macro History…", commandID: "macro.manage_delete_history", appDelegate: appDelegate))
        toolsMenu.addItem(commandItem(title: "Remove Deleted Macro History Entry…", commandID: "macro.remove_delete_history_entry", appDelegate: appDelegate))
        toolsMenu.addItem(commandItem(title: "Remove Deleted Macro History Entries…", commandID: "macro.remove_delete_history_entries", appDelegate: appDelegate))
        toolsMenu.addItem(commandItem(title: "Clear Deleted Macro History…", commandID: "macro.clear_delete_history", appDelegate: appDelegate))
        toolsMenu.addItem(commandItem(title: "Import Macro File…", commandID: "macro.import_file", appDelegate: appDelegate))
        toolsMenu.addItem(commandItem(title: "Export Named Macro…", commandID: "macro.export_named", appDelegate: appDelegate))
        toolsMenu.addItem(.separator())
        for feature in AttoSublimeFeatureBoundary.allCases {
            toolsMenu.addItem(commandItem(title: feature.menuTitle, commandID: feature.commandID, appDelegate: appDelegate))
        }

        let viewMenuItem = NSMenuItem()
        viewMenuItem.identifier = NSUserInterfaceItemIdentifier(AttoAccessibilityID.menu("View"))
        mainMenu.addItem(viewMenuItem)
        let viewMenu = NSMenu(title: "View")
        viewMenuItem.submenu = viewMenu
        viewMenu.addItem(commandItem(title: "Toggle Sidebar", commandID: "view.toggle_sidebar", appDelegate: appDelegate))
        viewMenu.addItem(commandItem(title: "Toggle Minimap", commandID: "view.toggle_minimap", appDelegate: appDelegate))
        viewMenu.addItem(commandItem(title: "Split Right", commandID: "view.split_right", appDelegate: appDelegate))
        viewMenu.addItem(commandItem(title: "Focus Next Pane", commandID: "view.focus_next_pane", appDelegate: appDelegate))
        viewMenu.addItem(commandItem(title: "Focus Previous Pane", commandID: "view.focus_previous_pane", appDelegate: appDelegate))
        viewMenu.addItem(commandItem(title: "Move Pane Left", commandID: "view.move_pane_left", appDelegate: appDelegate))
        viewMenu.addItem(commandItem(title: "Move Pane Right", commandID: "view.move_pane_right", appDelegate: appDelegate))
        viewMenu.addItem(commandItem(title: "Close Pane", commandID: "view.close_pane", appDelegate: appDelegate))
        viewMenu.addItem(.separator())
        let wrapMenuItem = NSMenuItem(title: "Word Wrap", action: nil, keyEquivalent: "")
        wrapMenuItem.identifier = NSUserInterfaceItemIdentifier(AttoAccessibilityID.menu("WordWrap"))
        let wrapMenu = NSMenu(title: "Word Wrap")
        wrapMenu.addItem(commandItem(title: "Off", commandID: "view.wrap.none", appDelegate: appDelegate))
        wrapMenu.addItem(commandItem(title: "By Character", commandID: "view.wrap.char", appDelegate: appDelegate))
        wrapMenu.addItem(commandItem(title: "By Word", commandID: "view.wrap.word", appDelegate: appDelegate))
        wrapMenuItem.submenu = wrapMenu
        viewMenu.addItem(wrapMenuItem)
        viewMenu.addItem(.separator())
        viewMenu.addItem(commandItem(title: "Fold Selection", commandID: "editor.fold_selection", appDelegate: appDelegate))
        viewMenu.addItem(commandItem(title: "Refresh Folding Ranges", commandID: "lsp.refresh_folding_ranges", appDelegate: appDelegate))
        viewMenu.addItem(commandItem(title: "Unfold at Cursor", commandID: "editor.unfold", appDelegate: appDelegate))
        viewMenu.addItem(commandItem(title: "Unfold All", commandID: "editor.unfold_all", appDelegate: appDelegate))

        let goMenuItem = NSMenuItem()
        goMenuItem.identifier = NSUserInterfaceItemIdentifier(AttoAccessibilityID.menu("Go"))
        mainMenu.addItem(goMenuItem)
        let goMenu = NSMenu(title: "Go")
        goMenuItem.submenu = goMenu
        goMenu.addItem(commandItem(title: "Go to File...", commandID: "go.file", appDelegate: appDelegate))
        goMenu.addItem(commandItem(title: "Go to Line...", commandID: "go.line", appDelegate: appDelegate))
        goMenu.addItem(commandItem(title: "Command Palette...", commandID: "workbench.command_palette", appDelegate: appDelegate))
        goMenu.addItem(commandItem(title: "Problems...", commandID: "lsp.problems", appDelegate: appDelegate))
        goMenu.addItem(commandItem(title: "Show Problems Panel", commandID: "lsp.show_problems_panel", appDelegate: appDelegate))
        goMenu.addItem(commandItem(title: "Document Symbols...", commandID: "lsp.document_symbols", appDelegate: appDelegate))
        goMenu.addItem(commandItem(title: "Workspace Symbols...", commandID: "lsp.workspace_symbols", appDelegate: appDelegate))
        goMenu.addItem(commandItem(title: "Show Last Symbols...", commandID: "lsp.show_last_symbols", appDelegate: appDelegate))
        goMenu.addItem(commandItem(title: "Show Symbol History...", commandID: "lsp.show_symbol_history", appDelegate: appDelegate))
        goMenu.addItem(commandItem(title: "Show Symbols Panel", commandID: "lsp.show_symbols_panel", appDelegate: appDelegate))
        goMenu.addItem(commandItem(title: "Document Colors...", commandID: "lsp.document_colors", appDelegate: appDelegate))
        goMenu.addItem(commandItem(title: "Pick Document Color...", commandID: "lsp.pick_document_color", appDelegate: appDelegate))
        goMenu.addItem(commandItem(title: "Show Document Colors Panel", commandID: "lsp.show_document_colors_panel", appDelegate: appDelegate))
        goMenu.addItem(commandItem(title: "Refresh Document Colors", commandID: "lsp.refresh_document_colors", appDelegate: appDelegate))
        goMenu.addItem(commandItem(title: "Completion", commandID: "lsp.completion", appDelegate: appDelegate))
        goMenu.addItem(commandItem(title: "Signature Help", commandID: "lsp.signature_help", appDelegate: appDelegate))
        goMenu.addItem(.separator())
        goMenu.addItem(commandItem(title: "Back", commandID: "go.back", appDelegate: appDelegate))
        goMenu.addItem(commandItem(title: "Forward", commandID: "go.forward", appDelegate: appDelegate))
        goMenu.addItem(commandItem(title: "Go to Matching Bracket", commandID: "go.matching_bracket", appDelegate: appDelegate))
        goMenu.addItem(.separator())
        goMenu.addItem(commandItem(title: "Go to Definition", commandID: "lsp.go_to_definition", appDelegate: appDelegate))
        goMenu.addItem(commandItem(title: "Go to Declaration", commandID: "lsp.go_to_declaration", appDelegate: appDelegate))
        goMenu.addItem(commandItem(title: "Go to Type Definition", commandID: "lsp.go_to_type_definition", appDelegate: appDelegate))
        goMenu.addItem(commandItem(title: "Go to Implementation", commandID: "lsp.go_to_implementation", appDelegate: appDelegate))
        goMenu.addItem(commandItem(title: "Find References", commandID: "lsp.find_references", appDelegate: appDelegate))
        goMenu.addItem(commandItem(title: "Show Last Locations...", commandID: "lsp.show_last_locations", appDelegate: appDelegate))
        goMenu.addItem(commandItem(title: "Show Location History...", commandID: "lsp.show_location_history", appDelegate: appDelegate))
        goMenu.addItem(commandItem(title: "Show Locations Panel", commandID: "lsp.show_locations_panel", appDelegate: appDelegate))
        goMenu.addItem(commandItem(title: "Show LSP Workbench Panel", commandID: "lsp.show_workbench_panel", appDelegate: appDelegate))
        goMenu.addItem(commandItem(title: "Show LSP Workbench Dock", commandID: "lsp.show_workbench_dock", appDelegate: appDelegate))
        goMenu.addItem(commandItem(title: "Show LSP Workbench History", commandID: "lsp.show_workbench_history", appDelegate: appDelegate))
        goMenu.addItem(commandItem(title: "Show LSP Workbench Pinned Results", commandID: "lsp.show_workbench_pinned_results", appDelegate: appDelegate))
        goMenu.addItem(commandItem(title: "Show LSP Workbench Selected History", commandID: "lsp.show_workbench_selected_history", appDelegate: appDelegate))
        goMenu.addItem(commandItem(title: "Jump to LSP Workbench First Result", commandID: "lsp.jump_workbench_first_result", appDelegate: appDelegate))
        goMenu.addItem(commandItem(title: "Jump to LSP Workbench Selected Result", commandID: "lsp.jump_workbench_selected_result", appDelegate: appDelegate))
        goMenu.addItem(commandItem(title: "Refresh LSP Workbench Selected Result", commandID: "lsp.refresh_workbench_selected_result", appDelegate: appDelegate))
        goMenu.addItem(commandItem(title: "Pin LSP Workbench Current Results", commandID: "lsp.pin_workbench_current_results", appDelegate: appDelegate))
        goMenu.addItem(commandItem(title: "Pin LSP Workbench Selected Result", commandID: "lsp.pin_workbench_selected_result", appDelegate: appDelegate))
        goMenu.addItem(commandItem(title: "Unpin LSP Workbench Current Results", commandID: "lsp.unpin_workbench_current_results", appDelegate: appDelegate))
        goMenu.addItem(commandItem(title: "Unpin LSP Workbench Selected Result", commandID: "lsp.unpin_workbench_selected_result", appDelegate: appDelegate))
        goMenu.addItem(commandItem(title: "Clear LSP Workbench Stale Results", commandID: "lsp.clear_workbench_stale_results", appDelegate: appDelegate))
        goMenu.addItem(commandItem(title: "Clear LSP Workbench Selected Stale Result", commandID: "lsp.clear_workbench_selected_stale_result", appDelegate: appDelegate))
        goMenu.addItem(commandItem(title: "Incoming Calls", commandID: "lsp.call_hierarchy_incoming", appDelegate: appDelegate))
        goMenu.addItem(commandItem(title: "Outgoing Calls", commandID: "lsp.call_hierarchy_outgoing", appDelegate: appDelegate))
        goMenu.addItem(commandItem(title: "Supertypes", commandID: "lsp.type_hierarchy_supertypes", appDelegate: appDelegate))
        goMenu.addItem(commandItem(title: "Subtypes", commandID: "lsp.type_hierarchy_subtypes", appDelegate: appDelegate))
        goMenu.addItem(commandItem(title: "Show Hierarchy Panel", commandID: "lsp.show_hierarchy_panel", appDelegate: appDelegate))
        goMenu.addItem(commandItem(title: "Refresh Hierarchy Panel", commandID: "lsp.refresh_hierarchy_panel", appDelegate: appDelegate))
        goMenu.addItem(commandItem(title: "Expand Hierarchy Selection", commandID: "lsp.expand_hierarchy_selection", appDelegate: appDelegate))
        goMenu.addItem(commandItem(title: "Rename Symbol", commandID: "lsp.rename", appDelegate: appDelegate))
        goMenu.addItem(commandItem(title: "Code Actions", commandID: "lsp.code_actions", appDelegate: appDelegate))
        goMenu.addItem(commandItem(title: "Code Lens Actions", commandID: "lsp.code_lens_actions", appDelegate: appDelegate))
        goMenu.addItem(commandItem(title: "Code Lens at Cursor", commandID: "lsp.code_lens_at_cursor", appDelegate: appDelegate))
        goMenu.addItem(commandItem(title: "Show Code Lens Panel", commandID: "lsp.show_code_lens_panel", appDelegate: appDelegate))
        goMenu.addItem(commandItem(title: "Refresh Code Lens", commandID: "lsp.refresh_code_lens", appDelegate: appDelegate))
        goMenu.addItem(commandItem(title: "Refresh Inlay Hints", commandID: "lsp.refresh_inlay_hints", appDelegate: appDelegate))
        goMenu.addItem(commandItem(title: "Show Inlay Hints Panel", commandID: "lsp.show_inlay_hints_panel", appDelegate: appDelegate))
        goMenu.addItem(commandItem(title: "Refresh Document Links", commandID: "lsp.refresh_document_links", appDelegate: appDelegate))
        goMenu.addItem(commandItem(title: "Show Document Links Panel", commandID: "lsp.show_document_links_panel", appDelegate: appDelegate))
        goMenu.addItem(commandItem(title: "Quick Fixes", commandID: "lsp.quick_fix", appDelegate: appDelegate))
        goMenu.addItem(commandItem(title: "Refactor Actions", commandID: "lsp.refactor", appDelegate: appDelegate))
        goMenu.addItem(commandItem(title: "Source Actions", commandID: "lsp.source_actions", appDelegate: appDelegate))
        goMenu.addItem(commandItem(title: "Organize Imports", commandID: "lsp.organize_imports", appDelegate: appDelegate))
        goMenu.addItem(commandItem(title: "Fix All", commandID: "lsp.fix_all", appDelegate: appDelegate))
        goMenu.addItem(commandItem(title: "Workspace Diagnostics", commandID: "lsp.workspace_diagnostics", appDelegate: appDelegate))
        goMenu.addItem(commandItem(title: "Show Workspace Problems Panel", commandID: "lsp.show_workspace_problems_panel", appDelegate: appDelegate))
        goMenu.addItem(commandItem(title: "Show Project LSP Status Events", commandID: "lsp.show_project_lsp_status", appDelegate: appDelegate))
        goMenu.addItem(commandItem(title: "Show Project LSP Process Health", commandID: "lsp.show_project_lsp_health", appDelegate: appDelegate))
        goMenu.addItem(commandItem(title: "Show Project LSP Process Health Log", commandID: "lsp.show_project_lsp_health_log", appDelegate: appDelegate))
        goMenu.addItem(commandItem(title: "Show Project LSP Health Dashboard", commandID: "lsp.show_project_lsp_dashboard", appDelegate: appDelegate))
        goMenu.addItem(commandItem(title: "Clear Project LSP Process Health Log", commandID: "lsp.clear_project_lsp_health_log", appDelegate: appDelegate))
        goMenu.addItem(commandItem(title: "Export Project LSP Process Health Log", commandID: "lsp.export_project_lsp_health_log", appDelegate: appDelegate))
        goMenu.addItem(commandItem(title: "Restart LSP Server", commandID: "lsp.restart_server", appDelegate: appDelegate))
        goMenu.addItem(commandItem(title: "Shut Down LSP Server", commandID: "lsp.shutdown_server", appDelegate: appDelegate))
        goMenu.addItem(commandItem(title: "Restart Project LSP Servers", commandID: "lsp.restart_project_servers", appDelegate: appDelegate))
        goMenu.addItem(commandItem(title: "Shut Down Project LSP Servers", commandID: "lsp.shutdown_project_servers", appDelegate: appDelegate))
        goMenu.addItem(commandItem(title: "Show Workspace Outline Panel", commandID: "lsp.show_workspace_outline_panel", appDelegate: appDelegate))

        return mainMenu
    }

    private static func commandItem(title: String, commandID: String, appDelegate: AttoAppDelegate) -> NSMenuItem {
        let binding = appDelegate.keyBinding(forCommandID: commandID)
        let item = NSMenuItem(
            title: title,
            action: #selector(AttoAppDelegate.commandMenuItemClicked(_:)),
            keyEquivalent: binding?.keyEquivalent ?? ""
        )
        item.keyEquivalentModifierMask = binding?.modifiers ?? []
        item.target = appDelegate
        item.representedObject = commandID
        item.identifier = NSUserInterfaceItemIdentifier(AttoAccessibilityID.commandMenuItem(commandID))
        return item
    }
}
