use super::LspResultSlot;

pub(super) fn from_response_method(method: &str) -> Option<LspResultSlot> {
    match method {
        "textDocument/hover" => Some(LspResultSlot::Hover),
        "textDocument/definition" => Some(LspResultSlot::Definition),
        "textDocument/declaration" => Some(LspResultSlot::Declaration),
        "textDocument/typeDefinition" => Some(LspResultSlot::TypeDefinition),
        "textDocument/implementation" => Some(LspResultSlot::Implementation),
        "textDocument/references" => Some(LspResultSlot::References),
        "textDocument/completion" => Some(LspResultSlot::Completion),
        "completionItem/resolve" => Some(LspResultSlot::CompletionResolve),
        "textDocument/signatureHelp" => Some(LspResultSlot::SignatureHelp),
        "textDocument/prepareRename" => Some(LspResultSlot::PrepareRename),
        "textDocument/rename" => Some(LspResultSlot::Rename),
        "textDocument/codeAction" => Some(LspResultSlot::CodeAction),
        "codeAction/resolve" => Some(LspResultSlot::CodeActionResolve),
        "workspace/executeCommand" => Some(LspResultSlot::ExecuteCommand),
        "textDocument/codeLens" => Some(LspResultSlot::CodeLens),
        "codeLens/resolve" => Some(LspResultSlot::CodeLensResolve),
        "textDocument/inlayHint" => Some(LspResultSlot::InlayHints),
        "inlayHint/resolve" => Some(LspResultSlot::InlayHintResolve),
        "textDocument/documentLink" => Some(LspResultSlot::DocumentLinks),
        "documentLink/resolve" => Some(LspResultSlot::DocumentLinkResolve),
        "textDocument/semanticTokens/full" => Some(LspResultSlot::SemanticTokensFull),
        "textDocument/semanticTokens/full/delta" => Some(LspResultSlot::SemanticTokensDelta),
        "textDocument/semanticTokens/range" => Some(LspResultSlot::SemanticTokensRange),
        "textDocument/documentSymbol" => Some(LspResultSlot::DocumentSymbols),
        "workspace/symbol" => Some(LspResultSlot::WorkspaceSymbols),
        "textDocument/foldingRange" => Some(LspResultSlot::FoldingRanges),
        "textDocument/selectionRange" => Some(LspResultSlot::SelectionRange),
        "textDocument/linkedEditingRange" => Some(LspResultSlot::LinkedEditingRange),
        "textDocument/diagnostic" => Some(LspResultSlot::DocumentDiagnostic),
        "workspace/diagnostic" => Some(LspResultSlot::WorkspaceDiagnostic),
        "textDocument/formatting" => Some(LspResultSlot::Formatting),
        "textDocument/rangeFormatting" => Some(LspResultSlot::RangeFormatting),
        "textDocument/documentColor" => Some(LspResultSlot::DocumentColor),
        "textDocument/colorPresentation" => Some(LspResultSlot::ColorPresentation),
        "textDocument/prepareCallHierarchy" => Some(LspResultSlot::PrepareCallHierarchy),
        "callHierarchy/incomingCalls" => Some(LspResultSlot::CallHierarchyIncoming),
        "callHierarchy/outgoingCalls" => Some(LspResultSlot::CallHierarchyOutgoing),
        "textDocument/prepareTypeHierarchy" => Some(LspResultSlot::PrepareTypeHierarchy),
        "typeHierarchy/supertypes" => Some(LspResultSlot::TypeHierarchySupertypes),
        "typeHierarchy/subtypes" => Some(LspResultSlot::TypeHierarchySubtypes),
        _ => None,
    }
}
