use super::LspResultSlot;

pub(super) fn method(slot: LspResultSlot) -> &'static str {
    match slot {
        LspResultSlot::Hover => "textDocument/hover",
        LspResultSlot::Definition => "textDocument/definition",
        LspResultSlot::Declaration => "textDocument/declaration",
        LspResultSlot::TypeDefinition => "textDocument/typeDefinition",
        LspResultSlot::Implementation => "textDocument/implementation",
        LspResultSlot::References => "textDocument/references",
        LspResultSlot::Completion => "textDocument/completion",
        LspResultSlot::CompletionResolve => "completionItem/resolve",
        LspResultSlot::SignatureHelp => "textDocument/signatureHelp",
        LspResultSlot::PrepareRename => "textDocument/prepareRename",
        LspResultSlot::Rename => "textDocument/rename",
        LspResultSlot::CodeAction => "textDocument/codeAction",
        LspResultSlot::CodeActionResolve => "codeAction/resolve",
        LspResultSlot::ExecuteCommand => "workspace/executeCommand",
        LspResultSlot::CodeLens => "textDocument/codeLens",
        LspResultSlot::CodeLensResolve => "codeLens/resolve",
        LspResultSlot::InlayHints => "textDocument/inlayHint",
        LspResultSlot::InlayHintResolve => "inlayHint/resolve",
        LspResultSlot::DocumentLinks => "textDocument/documentLink",
        LspResultSlot::DocumentLinkResolve => "documentLink/resolve",
        LspResultSlot::SemanticTokensFull => "textDocument/semanticTokens/full",
        LspResultSlot::SemanticTokensDelta => "textDocument/semanticTokens/full/delta",
        LspResultSlot::SemanticTokensRange => "textDocument/semanticTokens/range",
        LspResultSlot::DocumentSymbols => "textDocument/documentSymbol",
        LspResultSlot::WorkspaceSymbols => "workspace/symbol",
        LspResultSlot::FoldingRanges => "textDocument/foldingRange",
        LspResultSlot::SelectionRange => "textDocument/selectionRange",
        LspResultSlot::LinkedEditingRange => "textDocument/linkedEditingRange",
        LspResultSlot::DocumentDiagnostic => "textDocument/diagnostic",
        LspResultSlot::WorkspaceDiagnostic => "workspace/diagnostic",
        LspResultSlot::PublishDiagnostics => "textDocument/publishDiagnostics",
        LspResultSlot::DocumentColor => "textDocument/documentColor",
        LspResultSlot::ColorPresentation => "textDocument/colorPresentation",
        LspResultSlot::PrepareCallHierarchy => "textDocument/prepareCallHierarchy",
        LspResultSlot::CallHierarchyIncoming => "callHierarchy/incomingCalls",
        LspResultSlot::CallHierarchyOutgoing => "callHierarchy/outgoingCalls",
        LspResultSlot::PrepareTypeHierarchy => "textDocument/prepareTypeHierarchy",
        LspResultSlot::TypeHierarchySupertypes => "typeHierarchy/supertypes",
        LspResultSlot::TypeHierarchySubtypes => "typeHierarchy/subtypes",
        LspResultSlot::OnTypeFormatting => "textDocument/onTypeFormatting",
    }
}

pub(super) fn slot_name(slot: LspResultSlot) -> &'static str {
    match slot {
        LspResultSlot::Hover => "hover",
        LspResultSlot::Definition => "definition",
        LspResultSlot::Declaration => "declaration",
        LspResultSlot::TypeDefinition => "type_definition",
        LspResultSlot::Implementation => "implementation",
        LspResultSlot::References => "references",
        LspResultSlot::Completion => "completion",
        LspResultSlot::CompletionResolve => "completion_resolve",
        LspResultSlot::SignatureHelp => "signature_help",
        LspResultSlot::PrepareRename => "prepare_rename",
        LspResultSlot::Rename => "rename",
        LspResultSlot::CodeAction => "code_action",
        LspResultSlot::CodeActionResolve => "code_action_resolve",
        LspResultSlot::ExecuteCommand => "execute_command",
        LspResultSlot::CodeLens => "code_lens",
        LspResultSlot::CodeLensResolve => "code_lens_resolve",
        LspResultSlot::InlayHints => "inlay_hints",
        LspResultSlot::InlayHintResolve => "inlay_hint_resolve",
        LspResultSlot::DocumentLinks => "document_links",
        LspResultSlot::DocumentLinkResolve => "document_link_resolve",
        LspResultSlot::SemanticTokensFull => "semantic_tokens_full",
        LspResultSlot::SemanticTokensDelta => "semantic_tokens_delta",
        LspResultSlot::SemanticTokensRange => "semantic_tokens_range",
        LspResultSlot::DocumentSymbols => "document_symbols",
        LspResultSlot::WorkspaceSymbols => "workspace_symbols",
        LspResultSlot::FoldingRanges => "folding_ranges",
        LspResultSlot::SelectionRange => "selection_range",
        LspResultSlot::LinkedEditingRange => "linked_editing_range",
        LspResultSlot::DocumentDiagnostic => "document_diagnostic",
        LspResultSlot::WorkspaceDiagnostic => "workspace_diagnostic",
        LspResultSlot::PublishDiagnostics => "publish_diagnostics",
        LspResultSlot::DocumentColor => "document_color",
        LspResultSlot::ColorPresentation => "color_presentation",
        LspResultSlot::PrepareCallHierarchy => "prepare_call_hierarchy",
        LspResultSlot::CallHierarchyIncoming => "call_hierarchy_incoming",
        LspResultSlot::CallHierarchyOutgoing => "call_hierarchy_outgoing",
        LspResultSlot::PrepareTypeHierarchy => "prepare_type_hierarchy",
        LspResultSlot::TypeHierarchySupertypes => "type_hierarchy_supertypes",
        LspResultSlot::TypeHierarchySubtypes => "type_hierarchy_subtypes",
        LspResultSlot::OnTypeFormatting => "on_type_formatting",
    }
}
